### PR TITLE
Update docs to support OS X for getting started and use kind version >= 0.7

### PR DESCRIPTION
**Pull request by pdettori**
This PR goes together with https://github.com/open-cluster-management/registration-operator/pull/103 and addresses https://github.com/open-cluster-management/registration-operator/issues/102. 

The instructions for the patched version have been tested on OS X and Linux.

Signed-off-by: Paolo Dettori <dettori@us.ibm.com>

### CODE REVIEW

**Comment by mikeshng** [comment]
Thank you @pdettori please give me a day to play test this on my env and I will provide my feedback.

FYI @qiujian16 this is for updating the instruction to not rely on `0.7.0` version of `kind`.

**Comment by mikeshng** [comment]
Seems like https://github.com/open-cluster-management/registration-operator/pull/103 needs to be merged first(?) before we merge this PR. Please correct me if I am wrong.

**Comment by pdettori** [comment]
> Seems like [open-cluster-management/registration-operator#103](https://github.com/open-cluster-management/registration-operator/pull/103) needs to be merged first(?) 

Correct, the doc update is required once the other PR is merged.

**Comment by pdettori** [comment]
> FYI @qiujian16 this is for updating the instruction to not rely on `0.7.0` version of `kind`.

In addition, with this update, you can also run the `getting started` instructions on OS X, as the docker networking on Mac (differently than on Linux) does not allow to reach containers IP from the host, and therefore KUBECONFIG set with the internal server address does not work, even for kind v0.7.

**Comment by qiujian16** [comment]
Thanks, it is a great update!

/approve

@mikeshng leave lgtm to you when you have verified it.

**Comment by mikeshng** [comment]
I just tested this change with https://github.com/open-cluster-management/registration-operator/pull/103 and its working great! Thank you again @pdettori 

@qiujian16, before I can `lgtm` here. I think you need to review and merge the https://github.com/open-cluster-management/registration-operator/pull/103 first because this change has a dependency on that PR. Thanks.

**Comment by pdettori** [comment]
I noticed that `getting-started/install-application.md ` required also few updates. No updates were required in https://github.com/open-cluster-management/multicloud-operators-subscription. I have also documented that `export TRAVIS_BUILD=0` to get the Makefile to work in a local environment.

**Review by mikeshng — APPROVED** [review]

**Pull request merged**
